### ISSUE TITLE
On mac:  Could not load the 'puppet_apply' 

### ISSUE THREAD

**Issue by sahilsk** [neillturner/kitchen-puppet#118]
Hi, i'm trying to use 'kitchen.ci' with  puppet provisioner. Though it worked find if `chef_solo` is used. But with provisioner `puppet_apply` it throw following errors:

```
➜  practo-router-puppet kitchen create
-----> Starting Kitchen (v1.7.3)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'puppet_apply' provisioner from the load path. Please ensure that your provisioner is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```

Any  help here would be great. I am in dire need of an angel. 

Here is my Gemfile

```
# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "test-kitchen"
gem "kitchen-puppet"
gem "kitchen-vagrant"
gem "puppet"
gem "librarian-puppet"
```

Here is the `.kitchen.yml` file.

``` yml
---
driver:
  name: vagrant

provisioner:
    name: puppet_apply 
    puppet_version: 4.4.1
    manifests_path: manifests
    modules_path: modules
    hiera_data_path: hieradata
    require_chef_for_busser: true


platforms:
    - name: nocm_ubuntu-12.04
      driver_plugin: vagrant
      driver_config:
        box: nocm_ubuntu-12.04
        box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box

suites:
  - name: default
    provisioner:
      manifest: site.pp

```
