### ISSUE TITLE
Puppet masterless provisioner doesn't apply hiera

### ISSUE THREAD

**Issue by es1o** [neillturner/kitchen-puppet#163]
Hello, I've a configuration:

```
provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  require_puppet_collections: true
  hiera_data_path: hiera
  hiera_config_path: test
  puppet_apt_collections_repo: http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb

platforms:
  - name: ubuntu-16.04
    driver_config:
      require_puppet_collections: true
      puppet_version: 1.9.1-1xenial
      image: my-registryubuntu-16.04:1
      hostname: my hostname
```

I have defined hiera_data_path and hiera_config_path and it doesn't work.

kitchen runs thant command: `sudo -E env  /opt/puppetlabs/bin/puppet apply /tmp/kitchen/manifests/site.pp --modulepath=/tmp/kitchen/modules --fileserverconfig=/tmp/kitchen/fileserver.conf`

It doesn't provide hiera config and my puppet provisioning fails.
I tried to provide hiera.yaml to hiera_config_path and It didn't work too (I used hiera_config_path: test/hiera.yaml).

How can I use hiera with my puppet provisioning?
