### ISSUE TITLE
Puppet 4 always trys to install repo

### ISSUE THREAD

**Issue by sean797** [neillturner/kitchen-puppet#174]
https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet_apply.rb#L899 means `require_puppet_collections: true` is required to use the Puppet 4 path, however when this is set to true it will tried to install the puppet repo irespective of the `require_puppet_repo` option.

I have my puppet hosted in an internal mirror. Using the below snippet its still tried to install the repo from puppetlabs.

```yaml
provisioner:
  name: puppet_apply
  require_chef_for_busser: false
  manifests_path: manifests
  modules_path: modules
  require_puppet_repo: false
  custom_pre_apply_command: sudo yum install puppet -y
  require_puppet_collections: true
  puppet_detailed_exitcodes: true
  puppet_whitelist_exit_code:
    - 0
    - 2
```

**Comment by neillturner** [comment]
the line: 
  custom_pre_apply_command: sudo yum install puppet -y
will cause it to install the puppet repo
try removing that line.

**Comment by sean797** [comment]
Thanks for taking a look @neillturner setting `puppet_yum_collections_repo` doesn't quite work for me as the repo is provided and configured via subscription-manager 

> custom_pre_apply_command: sudo yum install puppet -y
will cause it to install the puppet repo
try removing that line.

That is installing the puppet agent not puppet repo :-)

**Comment by neillturner** [comment]
require_puppet_repo: false
 just causes puppet to not be installed from the puppet repo
If you set
require_puppet_collections: false
then kitchen puppet won't install puppet at all hopefully 
and then you can do what you like.
another possibility is to set 
custom_pre_install_command: 
to commands to setup 
 repo is provided and configured via subscription-manager and install puppet
if kitchen-puppet will only install puppet if it can't find a puppet installation

**Comment by sean797** [comment]
Thanks for your support @neillturner :+1:  The following worked in the end..

```yaml
provisioner:
  name: puppet_apply
  require_chef_for_busser: false
  manifests_path: manifests
  modules_path: modules
  require_puppet_repo: false
  custom_pre_install_command: sudo yum install puppet -y
  require_puppet_collections: true
  puppet_detailed_exitcodes: true
  puppet_whitelist_exit_code:
    - 0
    - 2
```

Just changed `custom_pre_apply_command` to `custom_pre_install_command`. I need `require_puppet_collections: true` to get the Puppet 4 path. Closing...
