### ISSUE TITLE
Could not load the 'puppet_hierawriter_apply' provisioner from the load path.

### ISSUE THREAD

**Issue by nvtkaszpir** [neillturner/kitchen-puppet#175]
Trying to use example code from the README.md section about using hierawriter - https://github.com/neillturner/kitchen-puppet/tree/2.0.0#hiera_writer_files-option
but it fails with message 
```Could not load the 'puppet_hierawriter_apply' provisioner from the load path.```

Looks like something was missing when merging this change?

**Steps to reproduce**

Gemfile
```ruby
# run `bundle install` to install packages
# in case of issues try `gem pristine --all`

source 'https://rubygems.org'

gem 'bundler'
gem 'busser'
gem 'inspec'
gem 'iconv'
gem 'kitchen-ansiblepush'
gem 'kitchen-ec2'
gem 'kitchen-inspec'
gem 'kitchen-lxc'
gem 'kitchen-puppet', '>=1.44.2'
gem 'kitchen-ssh'
gem 'kitchen-sshgzip'
gem 'kitchen-sync'
gem 'kitchen-transport-rsync'
gem 'kitchen-transport-sshtar'
gem 'kitchen-vagrant'
gem 'librarian-puppet'
gem 'puppet', '3.8.7'
gem 'puppet-lint'
gem 'test-kitchen'
gem 'vagrant-lxc' # requires 'vagrant plugin install vagrant-lxc; vagrant lxc sudoers'
gem 'vagrant-wrapper'
```

.kitchen.yml (notice, tuned to use LXC, but should be also the same under pristine setup)
```yaml
---
driver_plugin: lxc

driver:
  name: vagrant
  provider: lxc
  customize:
    aa_allow_incomplete: 1
    # enable fuse in containers
    #ppp
    cgroup.devices.allow: 'c 108:0 rwm'
    #fuse
    cgroup.devices.allow: 'c 10:229 rwm'
    #loop0
    cgroup.devices.allow: 'b 7:0 rwm'
    #tun
    cgroup.devices.allow: 'c 10:200 rwm'

provisioner:
  # name: puppet_apply
  name: puppet_hierawriter_apply
  manifests_path: vagrant/puppet/manifests/
  modules_path: "vagrant/puppet/modules/:vagrant/puppet/local_modules/"
  hiera_data_path: vagrant/puppet/hieradata
  puppet_verbose: true
  require_chef_for_busser: false
  custom_facts:
    location: vagrant
  hiera_writer_files:
    - datacenter/vagrant.yaml:
      logstash_servers: []
      hosts:
        10.1.2.3:
        - puppet
        - puppetdb

verifier:
  name: inspec
  sudo: true
  format: junit

platforms:
- name: centos7-lxc
  driver:
    box: st01tkh/centos7-64-lxc
  driver_config:
    username: vagrant
    password: vagrant
  provisioner:
    custom_pre_install_command: |
      sudo ip a
      sudo sed -i -e 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/fastestmirror.conf
      sudo yum clean all
      sudo yum install -y virt-what
      sudo yum update -y

suites:

  - name: app
```

**output:**
```text
18:29:21 kaszpir@waw-nw034 ~/src/derp  $ kitchen status
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'puppet_hierawriter_apply' provisioner from the load path. Please ensure that your provisioner is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Double-checking gems:
```bash
18:34:12 kaszpir@waw-nw034 ~/src/derp  $ gem list|grep -i kitchen
kitchen-ansiblepush (0.7.0, 0.4.0)
kitchen-ec2 (1.3.2, 1.2.0)
kitchen-inspec (0.19.0, 0.15.1)
kitchen-lxc (0.1.4)
kitchen-puppet (2.0.0)
kitchen-ssh (0.0.12, 0.0.11)
kitchen-sshgzip (0.0.3)
kitchen-sync (2.2.0, 2.1.1)
kitchen-transport-rsync (0.1.2)
kitchen-transport-sshtar (0.1.2)
kitchen-vagrant (1.1.0, 0.20.0)
test-kitchen (1.16.0, 1.13.0)
```
