### ISSUE TITLE
Need help with hiera-gpg implementation

### ISSUE THREAD

**Issue by anesterova** [neillturner/kitchen-puppet#180]
Hello everyone! 
Would be awesome if someone could help with setting this up.

Centos 7.

Hiera vagrant config:
```
:backends:
  - yaml
  - eyaml

:yaml:
  :datadir: /tmp/kitchen/hiera

:eyaml:
  :datadir: /tmp/kitchen/hiera
  :gpg_gnupghome: /home/vagrant/.gnupg

  :gpg_always_trust: true

:hierarchy:
  - "nodes/%{clientcert}"
  - "nodes/%{::datacenter}.pulse.prod/%{clientcert}"
  - "roles/%{::role}"
  - "%{::datacenter}"
  - "global"

:logger: console
:merge_behavior: deeper
```

.kitchen.yaml:
```
provisioner:
  name: puppet_apply
  modules_path: ../.tmp
  manifests_path: test/integration
  hiera_data_path: ../hieradata
  hiera_config_path: ../hiera_kitchen.yaml
  puppet_future_parser: true

  custom_facts:
    role: jenkins_server
  install_custom_facts: true

  hiera_deep_merge: true
  hiera_eyaml_gpg: true
  hiera_eyaml_gpg_recipients: hiera/hiera-eyaml-gpg.recipients
  hiera_eyaml_gpg_secring: hiera/secring.gpg
  hiera_eyaml_gpg_pubring: hiera/pubring.gpg
```

I put keys to hieradata folder:
```
$ ll  hieradata/
total 104
-rw-r--r--    1 ao  staff    74B Aug  2 11:02 hiera-eyaml-gpg.recipients
-rw-------    1 ao  staff   6.7K Aug  2 11:26 pubring.gpg
drwxr-xr-x  102 ao  staff   3.4K Aug  2 11:02 roles/
-rw-------    1 ao  staff   4.8K Aug  2 11:26 secring.gpg
```

The error i am getting:
```
       Error: Error from DataBinding 'hiera' while looking up 'jenkins::user_hash': GPG command (gpg --homedir /home/vagrant/.gnupg --quiet --no-secmem-warning --no-permission-warning --no-tty --yes --decrypt) failed with: gpg: can't connect to the agent: IPC connect call failed
       gpg: problem with the agent: No agent running
       gpg: decryption failed: No secret key
```

I tried to add import gpg command in custom_pre_apply_command section, but getting the same error.
```
  custom_pre_apply_command: 'sudo -E gpg --import /home/vagrant/.gnupg/secring.gpg;'
```

gpg agent is running on the box:
```
[root@jenkins-vagrant-centos-7 vagrant]# ps aux|grep gpg
root      9016  0.0  0.0 121376   952 ?        Ss   09:39   0:00 gpg-agent --daemon --use-standard-socket
root      9052  0.0  0.0 112644   956 pts/0    R+   09:44   0:00 grep --color=auto gpg
[root@jenkins-vagrant-centos-7 vagrant]#
```

And interesting that hiera-gpg (decryption) works inside the vagrant:
```
[root@jenkins-vagrant-centos-7 vagrant]# export FACTERLIB='/tmp/kitchen/facter';  export MANIFESTDIR='/tmp/kitchen/manifests'; puppet apply -e 'notify { $role: }'
Notice: Compiled catalog for jenkins-vagrant-centos-7.vagrantup.com in environment production in 0.01 seconds
Notice: jenkins_server
Notice: /Stage[main]/Main/Notify[jenkins_server]/message: defined 'message' as 'jenkins_server'
Notice: Finished catalog run in 0.01 seconds
[root@jenkins-vagrant-centos-7 vagrant]# export FACTERLIB='/tmp/kitchen/facter';  puppet apply -e '$jenkins_version = hiera('jenkins_version') notify { $jenkins_version: }' --hiera_config=/tmp/kitchen/hiera.yaml
Notice: Compiled catalog for jenkins-vagrant-centos-7.vagrantup.com in environment production in 0.03 seconds
Notice: 2.60.2-1.1
Notice: /Stage[main]/Main/Notify[2.60.2-1.1]/message: defined 'message' as '2.60.2-1.1'
Notice: Finished catalog run in 0.01 seconds
[root@jenkins-vagrant-centos-7 vagrant]#
```

Also tried with centos 6, got this error with the same config file:
```
       Error: Could not run: Could not retrieve facts for jenkins-vagrant-centos-6.vagrantup.com: undefined method `require_relative' for main:Object
```
Tried to use rvm to have 2.3.0 ruby for centos 6 - same error.

I am running out of ideas, so any help is appreciated!  
Thanks in advance!
