### ISSUE TITLE
Passing custom facts to provisioner that has a hash results in garbage values

### ISSUE THREAD

**Issue by cgetzen** [neillturner/kitchen-puppet#182]
Example:
.kitchen.yml

```
provisioner:
  name: puppet_apply
  install_custom_facts: true
  custom_facts:
    my_hash:
      - one: hello
      - two: world
    other_hash:
      one: hello
      two: world
```

Returned kitchen.rb file:
```
Facter.add(:my_hash) do
  setcode do
    "[{:"one"=>"hello"}, {:"two"=>"world"}]"
  end
end

Facter.add(:other_hash) do
  setcode do
    "{:one=>"hello", :two=>"world"}"
  end
end
```

Expected output:
```
Facter.add(:my_hash) do
  setcode do
    {:one=>"hello", :two=>"world"}
  end
end
```
