### ISSUE TITLE
sync environments dir

### ISSUE THREAD

**Issue by ebenezar-mccoy** [neillturner/kitchen-puppet#189]
Hello,

i have case to test whole /etc/puppetlabs/code with main hiera.yaml and environments with it's own hieras

my kitchen.yml

```
---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: puppet_apply
  puppet_debug: true
  puppet_verbose: true
  require_chef_for_busser: false
  require_puppet_repo: false
  manifests_path: manifests
  modules_path: modules
  hiera_data_path: hieradata
  puppet_environmentpath_remote_path: /tmp/environments
  puppet_environment: some_environment
  puppet_environment_remote_hieradata_path: data

platforms:
- name: ubuntu

suites:
 - name: default
   driver_config:
     privileged: true
     run_command: /sbin/init
     dockerfile: Dockerfile
     hostname: some_name_for_facts
```

i currently have separate process uploading the environments directory with rsync  to /tmp/environments

then i run converge once again to check for results,

my question: is there configuration option that  copy environments directory for me ?
