### ISSUE TITLE
Puppet command not found error

### ISSUE THREAD

**Issue by alepeltier** [neillturner/kitchen-puppet#209]
Hello,

I'm running a kitchen test script based off the README example. This is my platforms code block:

```
platforms:
  - name: nocm_ubuntu-12.04
    driver_plugin: vagrant
    driver_config:
      box: nocm_ubuntu-12.04
      box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
```

The script runs perfectly fine when set nocm_ubuntu-12.04 as the platform but when I use the puppetlabs/centos-6.6-32-nocm vagrant box I get an error saying puppet is not installed. The only difference is I haven’t provided the box url as I know it. From the looks of it Kitchen installs puppet when it runs so I can’t work out why puppet wouldn’t be installed. Is this a bug or am I missing something?

Any advice you could give me would be amazing.

Thanks 

Alex
