### ISSUE TITLE
how to redefine provisioner options for a specific platform?

### ISSUE THREAD

**Issue by kostyrevaa** [neillturner/kitchen-puppet#45]
I need to test against centos 5 but puppet_yum_repo defaults to 6 version.
Is it possible to redefine this option at platforms level?

**Comment by kostyrevaa** [comment]
```
platforms:
  - name: centos-6.4
  - name: centos-7
  - name: centos-5.9
    provisioner:
      puppet_yum_repo: 'http://yum.puppetlabs.com/puppetlabs-release-el-5.noarch.rpm'
```
