### ISSUE TITLE
Default Puppetlabs Ubuntu deb version is too old (precise)

### ISSUE THREAD

**Issue by themasterchef** [neillturner/kitchen-puppet#67]
## Problem

In puppet_apply.rb, we see that the default Puppet APT repo is very old (Ubuntu precise)

```
default_config :puppet_apt_repo, 'http://apt.puppetlabs.com/puppetlabs-release-precise.deb'
```

When using a Vagrant + Kitchen setup like this:

```
 platforms:
   - name: ubuntu-14.04
```

It fails to detect that '14.04' and sticks with the 'precise' URL. This breaks installation, because the `puppet` and `hiera-puppet` packages in this repo have broken dependencies:

```
The following packages have unmet dependencies:
        hiera-puppet : Depends: puppet but it is not going to be installed
       E: Unable to correct problems, you have held broken packages.
```

## Fix

Therefore it might be a good plan to update this default config to at least point at the trusty package.

## Workaround

In the meantime, this kitchen.yml setup seems to get past this problem stage:

```
provisioner:
  name: puppet_apply
  require_chef_for_busser: false
  puppet_apt_repo: http://apt.puppetlabs.com/puppetlabs-release-trusty.deb

platforms:
  - name: ubuntu-14.04
```
