### ISSUE TITLE
Test best practice 

### ISSUE THREAD

**Issue by gomex** [neillturner/kitchen-puppet#84]
I don't know what best place to ask that. Sorry if I am place in wrong place.

What is the best practice to organize kitchen puppet tests?

I am creating one suite test per profile, but I don't know the best practice to config this in kitchen.yml file. How do you configure your tests? Do you use more than one suites? Do you configure one per module, profile or roles? How do you organize that in kitchen.yml file?

Sorry again if there is a better place to ask this :)

**Comment by grubernaut** [comment]
I setup a single test suite per role we have defined in hiera. I also use the `custom_facts` parameter to supply each test-suite with custom facter facts.

```
....
suites:
  - name: production-web
    provisioner:
      custom_facts:
        role: web
        environment: production
....
```

Then inside of my `test/integration/<suite>/serverspec/` directory, there's tests for each test-suite defined in test-kitchen.

Hope this helps
